#!/usr/bin/env bash
# Enables clicking by tapping in the touchpad.
# This configuration is not persistent and must be added to .profile, otherwise it will reset on startup.

source "$(dirname "$(realpath "${0}")")/utils/logging.bash"
source "$(dirname "$(realpath "${0}")")/utils/baseutils.bash"

# Check required dependencies.
dependencyExists 'xinput'

touchpadDeviceName='Synaptics TM3471-020'
echoInfo "configuring touchpad device: ${touchpadDeviceName}"

# Confiugre tapping
tappingPropertyName='libinput Tapping Enabled'
echoInfo "setting property ${tappingPropertyName} to 1"
xinput set-prop "${touchpadDeviceName}" "${tappingPropertyName}" 1

# Restart touchpad in case it got stuck
# see https://askubuntu.com/q/528293
xinput disable "${touchpadDeviceName}"
xinput enable "${touchpadDeviceName}"
