#!/bin/bash

export GENERATED_PALETTE_1=`xrdb -query | grep generated1: | grep -oE "#[0-9a-f]+"`
export GENERATED_PALETTE_5=`xrdb -query | grep generated5: | grep -oE "#[0-9a-f]+"`
export GENERATED_PALETTE_10=`xrdb -query | grep generated10: | grep -oE "#[0-9a-f]+"`

export APP_TO_RUN=`cat\
	<(pacman -Q | awk '{print $1}')\
	<(find /usr/bin -printf "%f\n")\
	| sort | uniq | dmenu -l 10 \
          -nb "$GENERATED_PALETTE_1" \
          -nf "$GENERATED_PALETTE_5" \
          -sf "$GENERATED_PALETTE_10" \
          -sb "$GENERATED_PALETTE_1" \
        -p "Run application" -i` > /tmp/test

if [ "$APP_TO_RUN" != "" ]; then
	notify-send -u low "Running app" "$APP_TO_RUN"
fi
$APP_TO_RUN

