#!/bin/bash

var="$(cat)"

function getColor() {
  colorNumber="${1}"
  xrdb -query | grep "generated${colorNumber}:" | grep -oE "#[0-9a-f]+"
}

ROFI_THEMES_DIRECTORY="${HOME}/.local/share/rofi/themes"
if [ ! -d "${ROFI_THEMES_DIRECTORY}" ]; then
  echo "creating directory ${ROFI_THEMES_DIRECTORY}"
  mkdir --parents "${ROFI_THEMES_DIRECTORY}"
fi

ROFI_THEME_FILE_NAME="${ROFI_THEMES_DIRECTORY}/rofi-theme-generated"
ROFI_THEME_FILE="${ROFI_THEME_FILE_NAME}.rasi"
ROFI_THEME="""
* {
    test-color:                  $(getColor 10);
    prompt-text-color:           $(getColor 15);
    prompt-entry-text-color:     $(getColor 11);

    window-background:           $(getColor 1)e1;
    input-bar-background:        $(getColor 1)e1;
    message-background:          $(getColor 1)e1;
    input-bar-border-background: $(getColor 7)e1;
    active-element-background:   $(getColor 2)e1;
}
* {
    font:   \"Roboto 12\";

    background-color:   transparent;
    text-color:         @test-color;

    margin:     0px;
    padding:    0px;
    spacing:    0px;
}

window {
    location:       center;
    width:          480;
    border-radius:  24px;
    
    background-color:   @window-background;
}

mainbox {
    padding:    12px;
}

inputbar {
    background-color:   @input-bar-background;
    border-color:       @input-bar-border-background;

    border:         2px;
    border-radius:  16px;

    padding:    8px 16px;
    spacing:    8px;
    children:   [ prompt, entry ];
}

prompt {
    text-color: @prompt-text-color;
}

entry {
    placeholder:        \"Search\";
    placeholder-color:  @prompt-entry-text-color;
}

message {
    margin:             12px 0 0;
    border-radius:      16px;
    border-color:       @message-background;
    background-color:   @message-background;
}

textbox {
    padding:    8px 24px;
}

listview {
    background-color:   transparent;

    margin:     12px 0 0;
    lines:      8;
    columns:    1;

    fixed-height: false;
}

element {
    padding:        8px 16px;
    spacing:        8px;
    border-radius:  16px;
}

element normal active {
    text-color: @active-element-background;
}

element selected normal, element selected active {
    background-color:   @active-element-background;
}

element-icon {
    size:           1em;
    vertical-align: 0.5;
}

element-text {
    text-color: inherit;
}
"""
echo "${ROFI_THEME}" > "${ROFI_THEME_FILE}"

echo "${var}" | rofi -dmenu -lines 10 \
                     -theme "${ROFI_THEME_FILE_NAME}" \
                     -p "${1}" -i
