#!/usr/bin/env bash

SCREEN_LAYOUT_DIRECTORY="${HOME}/.screenlayout"
selectedScreenLayout="$(find -L "${SCREEN_LAYOUT_DIRECTORY}" -type f -printf "%f\n" | sort | dmenu_generated "Select screen layout")"

"${SCREEN_LAYOUT_DIRECTORY}/${selectedScreenLayout}"
